title: mobinfo
tagline: Quickly get detailled technical characteristics and specifications of any smartphone directly from your favorite terminal.
description: A command-line tool written in Bash 4.2+ that offers comprehensive and up-to-date mobile phone information from various online websites.
url: https://grm34.github.io/mobinfo
author:
  name: darkmaster @grm34
  url: https://github.com/grm34
google_analytics: G-XRXTP3G5KE
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
theme: jekyll-theme-midnight
